[workspace]
authors = ["mourya96 <amcnagesh@gmail.com>"]
channels = ["conda-forge"]
name = "IITM-Notes"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
numpy = ">=2.3.0,<3"
pandas = ">=2.3.0,<3"
matplotlib = ">=3.10.3,<4"
seaborn = ">=0.13.2,<0.14"
